### ISSUE TITLE
Add discord web stealer

### ISSUE THREAD

**Issue by ZadgeIsCool** [KSCH-58/Malicord#1]
ADD DISCORD WEB STEALER PLZ

**Comment by KSCH-58** [comment]
What do you mean by "web stealer" ?

**Comment by ZadgeIsCool** [comment]
yes

**Comment by KSCH-58** [comment]
Okay btw what do you mean????

**Comment by ZadgeIsCool** [comment]
discord.com stealer

**Comment by ZadgeIsCool** [comment]
not only discord application

**Comment by KSCH-58** [comment]
It's grab also web tokens look inside "social/Discord/Discord.txt" btw only 2 tokens Will apear on webhook (Discord webhook cannot have bigger embed)

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/KSCH-58/Malicord/assets/34542867/05aa35b8-bca1-4e0e-a6fe-f5c68a450c7d)

**Comment by KSCH-58** [comment]
Also It's grabbing "discord canary" & "ptb"

**Comment by ZadgeIsCool** [comment]
nothing else

**Comment by ZadgeIsCool** [comment]
only "Browsers" and "System" no "Social"

**Comment by ZadgeIsCool** [comment]
i am logged into discord website and it is not showing me email, password and token

**Comment by KSCH-58** [comment]
Okay im gonna patch this

**Comment by ZadgeIsCool** [comment]
okay thank you

**Comment by ZadgeIsCool** [comment]
also add icon

**Comment by ZadgeIsCool** [comment]
and remove this 
![image](https://github.com/KSCH-58/Malicord/assets/34542867/fcd0fac8-92cf-4fcc-8e67-c4bd1cc7d351)

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/KSCH-58/Malicord/assets/34542867/5aa5e5a3-2bc6-454f-95bc-c35e0b1042db)

**Comment by KSCH-58** [comment]
Other file customization are only available with nova sentinel (the premium versión)

**Comment by ZadgeIsCool** [comment]
ok

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/KSCH-58/Malicord/assets/34542867/dfab9e78-dd73-440b-a5c6-43a3dc9014d7)

**Comment by ZadgeIsCool** [comment]
nevermind i fixed it :)

**Comment by ZadgeIsCool** [comment]
just fix discord web stealer

**Comment by ZadgeIsCool** [comment]
also bro add discord password stealer not only token and email

**Comment by ZadgeIsCool** [comment]
and old password and new password and old email and new email

**Comment by ZadgeIsCool** [comment]
1. Fix discord web stealer

2. add discord password stealer

3. add old and new password and email

**Comment by ZadgeIsCool** [comment]
hello? are you gonna update it?
